[package]
name = "bedrock-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bedrock_core = { path = "bedrock_core" }

nbt = { path = "nbt" }

proto = { path = "proto" }
proto_core = { path = "proto_core" }
proto_derive = { path = "proto_derive" }

packs = { path = "packs" }
world = { path = "world", optional = true }

form = { path = "form" }

paletted_storage = { path = "paletted_storage", optional = true }

[features]
default = []
world = ["dep:world", "dep:paletted_storage"]
