[package]
name = "bedrock-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bedrock_core = { path = "bedrock_core" }

nbt = { path = "nbt" }

proto = { path = "proto" }
proto_core = { path = "proto_core" }
proto_derive = { path = "proto_derive" }

packs = { path = "packs" }

world = { path = "world" }

form = { path = "form" }