[package]
name = "bedrock-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bedrockrs_core = { path = "core" }

bedrockrs_nbt = { path = "nbt" }

bedrockrs_proto = { path = "proto" }
bedrockrs_proto_core = { path = "proto_core" }
bedrockrs_proto_derive = { path = "proto_derive" }

bedrockrs_addons = { path = "addons" }

bedrockrs_form = { path = "form" }

bedrockrs_world = { path = "world", optional = true }
bedrockrs_paletted_storage = { path = "paletted_storage", optional = true }

[features]
default = []
world = ["dep:bedrockrs_world", "dep:bedrockrs_paletted_storage"]
