[package]
name = "bedrockrs_world"
version = "0.1.0"
edition = "2021"

[dependencies]
bedrockrs_core = { path = "../core" }
bedrockrs_nbt = { path = "../nbt" }
bedrockrs_paletted_storage = { path = "../paletted_storage" }

mojang-leveldb = "0.4"
thiserror = "1.0"
byteorder = "1.5"
