[package]
name = "world"
version = "0.1.0"
edition = "2021"

[dependencies]
bedrock_core = { path = "../bedrock_core" }
paletted_storage = { path = "../paletted_storage" }
nbt = { path = "../nbt" }

mojang-leveldb = "0.4"
thiserror = "1.0"
byteorder = "1.5"
