[package]
name = "bedrockrs_paletted_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
bedrockrs_core = { path = "../core" }

nbtx = { git = "https://github.com/bedrock-crustaceans/nbtx" }

byteorder = "1.5"
