[package]
name = "bedrockrs_paletted_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
bedrockrs_core = { path = "../core" }
bedrockrs_nbt = { git = "https://github.com/bedrock-crustaceans/bedrockrs-nbt" }

byteorder = "1.5"
