[package]
name = "text"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = "2.0"
quote = "1.0"
lazy_static = { version = "1.4.0" }

html_parser = "0.7"
